### ISSUE TITLE
Count over bundle

### ISSUE THREAD

**Issue by ChristophLeonhardt** [PolMine/polmineR#90] opened 2019-06-13 13:24 UTC
If I am not mistaken, it should be possible to count over a bundle object (for example to subset partitions which meet a certain threshold). This doesn't seem to work anymore:

`speeches_ger <- as.speeches("GERMAPARL", s_attribute_name = "speaker", gap = 100)
count(speeches_ger, "Freiheit")
   |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed = 00s
... adding total number of hits (col 'TOTAL', verbose = verbose)
Warning message:
In .local(.Object, ...) :
  An argument has been passed into the cpos()-method via three dots (...) that is unknown.`

**Comment by ablaette** [comment] 2019-07-13 17:38
The issue is smaller than I had thought at first: Please note that you see a *warning*, not an *error*. Your example returns the correct result. Counting over a `partition_bundle` had not stopped to work correctly.

But this is only half of the truth. It is a confusing warning message that you stumbled over and I am lucky your reported it. To have greater control over arguments that are passed around, I had introduced a check on arguments coming into the `cpos()`-method (the worker behind all counting operations) a few weeks ago. You get the warning if anything arrives at the method via the three dots (`...`) that is not actually processed.

So this is what happened: An argument `encoding` that has become superflous with the introduction of the `corpus` class was passed into the `cpos()` method from the `hits()`-method (called by `count()`), triggering the warning.

The excess argument has been removed, I cleaned up the code of the `hits()`-method for `partition_bundle` objects to make it easier to understand, and wrote a test to enhance the confidence that counting over a `partition_bundle` really, really works. 

The changes are part of a new polmineR version v0.7.11.9026 I just pushed to the dev branch.

To check that everything works, please see the following minimal example, or the examples in the documentation of the `count()`-method.

```r
library(polmineR)
use("GermaParl")

cnt_int <- corpus("GERMAPARLMINI") %>%
  as.speeches(s_attribute_name = "speaker") %>%
  count(query = "Integration")

show(cnt_int)
```

**Comment by ChristophLeonhardt** [comment] 2019-07-15 14:30
You are right. It is a warning, not an error, and your explanation makes things more clear. 

Just for your information: The same warning is shown if you count over a corpus, so that's consistent. 

`count("GERMAPARL", query = '"Integrat.*"', cqp = TRUE)`

**Comment by ablaette** [comment] 2019-07-15 21:50
Good to know that the issue occurs with `count()`, too. I have removed the cause for the warning, and will close the issue.

**Closed by ablaette** 2019-07-15 21:50 UTC
