### ISSUE TITLE
stoplist/stopwords in context_method/cooccurrences

### ISSUE THREAD

**Issue by mxi-hug** [PolMine/polmineR#28] opened 2017-11-13 09:39 UTC
it's not a bug, it's a feature, but one leading to unexpected behaviour...
the filtering mechanism for stopwords implemented in the context method excludes not only the terms given in the function parameter but always the complete nodes containing the stopwords/positivewords.

https://github.com/PolMine/polmineR/blob/dev/R/context_method.R#L137 (for positivelist)
https://github.com/PolMine/polmineR/blob/dev/R/context_method.R#L156 (for stoplist)

This seems helpful, when it is used to filter for meaningful concepts (e.g. Integration +- Islam) but makes it impossible to filter for frequent classic stopwords without significant meaning (conjunctions, articles etc). This is especially problematic for cooccurrences (hits can be filtered afterwards, but this makes the calculations rather inefficient).

I'm not entirely sure whether it's best to simply drop by "word_id" instead by "position" or to implement a switch making both options possible.

**Comment by PolMine** [comment] 2018-12-13 22:21
Dear Max, 

sorry for taking way to long to respond. I tried to find a reproducible example, but the links in you message do not work any more. Can you provide me with an example?

Andreas

**Comment by PolMine** [comment] 2018-12-17 22:13
Dear Max, 

I just thought I should reconsider your question. The arguments `positivelist` and `negativelist` are intended to filter out matches for `query`, if a word on these vectors is / is not in the context of a match for the query. I think that subsetting the result of the statistical computation as follows what you might have been looking for. 

```r
library(polmineR)
library(magrittr)
library(tm)
use("GermaParl")

# without pipe
a <- cooccurrences("GERMAPARL", query = "Islam")
b <- subset(a, !is.na(ll))
y <- subset(b, !word %in% tm::stopwords("de"))

# using pipe operator
a <- cooccurrences("GERMAPARL", query = "Islam") %>%
  subset(!is.na(ll)) %>%
  subset(!word %in% tm::stopwords("de"))
```
Though I have been working a lot on the documentation of the statistical tests (ll, and chisquare) lately, I do not think the documentation of the `cooccurrences()`-method is sufficiently expressive as a far as examples are concerned. So I will extend this.

Assuming that my answer addresses your point, I will close this issue. Please re-open it, if I missed your point!

Andreas

**Closed by PolMine** 2018-12-17 22:13 UTC

**Comment by mxi-hug** [comment] 2018-12-18 08:09
Hey, sorry for not providing an example and thanks for the clarification in your second comment. I realized that I didn't fully understand the important distinction between "stoplist" and "stopwords". They sound similar but require a different workflow to filter.
