### ISSUE TITLE
kwic with p-attribute = "lemma"

### ISSUE THREAD

**Issue by jkrss** [PolMine/polmineR#70] opened 2019-02-11 21:34 UTC
When using kwic() with p-attribute = "lemma" (instead of "word") I can't transform the output into a dataframe properly. The cells for left, node and right are empty (but the dataframe has as many rows as hits in the kwic). Kwic itself works correctly (right number of hits etc.).

**Comment by PolMine** [comment] 2019-02-11 21:59
Thanks for raising the issue! But I am afraid I will need further information, or code to reproduce the issue. 

What version of polmineR are you working with `packageVersion(polmineR)`? Using the recent development version (0.7.11.9001), this works for me.

```r
library(polmineR)
use("GermaParl")

kwic("GERMAPARL", query = "Integration", p_attribute = "lemma")
kwic("GERMAPARL", query = "Integration", p_attribute = "lemma") %>%
  as.data.frame()
```

Thus, I do not immediately manage to reproduce the issue.

**Comment by jkrss** [comment] 2019-02-12 08:31
Updating to the recent development version solved the problem!

**Comment by PolMine** [comment] 2019-02-12 08:35
Good to hear this, so I will close the issue. The next CRAN release of polmineR will tage another few weeks (to consolidate some non standard evaluation stuff to create subcorpora), so I hope it is ok to stick with the development version in the meantime. Andreas

**Closed by PolMine** 2019-02-12 08:35 UTC
