### ISSUE TITLE
Error in subset method for remote_corpus class

### ISSUE THREAD

**Issue by Thore91** [PolMine/polmineR#181] opened 2020-12-14 12:51 UTC
When attempting to subset remote_corpus "FAZ_MIGPRESS" like
```
faz <- corpus("MIGPRESS_FAZ", server = "faz.migpress.de", restricted = TRUE)
faz_article <- subset(faz, article_id == "FAS_200109_11098")
```
I receive the error 
> Error in .local(x, ...) : object 'article_id' not found

checking the s_attributes, 'article_id' is still part of them. also, when performing a similar query for a local corpus, the command works:

```
parl <- corpus("GERMAPARLMINI")
speeches <- parl %>%
     subset(date == "2009-10-27")
```

I am using the dev-version of polmineR 0.8.5.9012

**Comment by ablaette** [comment] 2020-12-14 13:16
Thanks for reporting this issue. I am quite sure it is an unintended side effect of issue #162 : As it seems, you cannot use 'plain' expressions any more, any expression needs to be substituted.

```r
faz_article <- subset(faz, substitute(article_id %in% "FAS_200109_11098"))
```

**Comment by Thore91** [comment] 2020-12-14 13:41
that solves it!

**Comment by ablaette** [comment] 2020-12-14 13:53
I do not think the issue is already solved - substituting expressions should not be necessary by default; I think I should reconstruct the old way!

**Comment by ablaette** [comment] 2020-12-17 07:54
Returning to this issue, I cannot reproduce the error we encountered when passing a plain expression to the remote server. This is the code I used:

```r
library(polmineR)
packageVersion("polmineR")
faz <- corpus("MIGPRESS_FAZ", restricted = TRUE)
faz_article <- subset(faz, article_id == "FAS_200109_11098")
```

I would have expected this does not work an more - but it does. And I do not have any idea what might be different from the situation we had a few days ago. The only clue I have is to check whether we had a server-side update of polmineR.

**Comment by Thore91** [comment] 2020-12-17 13:09
I can confirm that the error cannot be reproduced. `faz_article <- subset(faz, article_id == "FAS_200109_11098")` works for me as well now.

What cannot be done is passing a vector to the `subset` function.

like
```
library(polmineR)
faz <- corpus("MIGPRESS_FAZ", restricted = TRUE)
faz_sample <- c("FAZ_201410_33002", "FAZ_200006_90801", "FAZ_201402_30085", "FAZ_201404_30485", "FAZ_200309_77734")
faz_article <- subset(faz, substitute(article_id %in% faz_sample))
```

> Error in ocpu_exec(fn = "subset", corpus = x@corpus, server = x@server,  : 
  Bad Request (HTTP 400).

**Comment by ablaette** [comment] 2020-12-18 08:03
I just pushed a new polmineR version to the dev branch that will not require by default that the incoming expression is already substituted. You can pass a plain expression with logical operators again. This is the code I used for testing:

```r
faz <- corpus("MIGPRESS_FAZ", server = "faz.migpress.de", restricted = TRUE)

faz_sc1 <- subset(faz, substitute(article_id == "FAS_200109_11098"))
faz_sc2 <- subset(faz, article_id == "FAS_200109_11098")


faz_article <- "FAS_200109_11098"
faz_sc4 <- subset(faz, substitute(article_id %in% faz_article, list(faz_article = faz_article)))

faz_articles <- c(
  "FAZ_201410_33002",
  "FAZ_200006_90801",
  "FAZ_201402_30085",
  "FAZ_201404_30485",
  "FAZ_200309_77734"
)
faz_sc4 <- subset(faz, substitute(article_id %in% faz_sample, list(faz_sample = faz_sample)))

```

**Comment by ablaette** [comment] 2020-12-18 12:54
I am glad I found a way to include minimal tests on the openCPU functionality in the package, see:
https://github.com/PolMine/polmineR/blob/dev/tests/testthat/test_opencpu.R

Now I feel sufficiently confident to close the issue. The documentation should also be using the newly won ability to test remote access - but this request should be left to another issue.

**Closed by ablaette** 2020-12-18 12:54 UTC
