### ISSUE TITLE
Special characters in filename

### ISSUE THREAD

**Issue by ablaette** [PolMine/polmineR#66] opened 2019-01-28 14:05 UTC
There is still a problem with filenames that include special characters (e.g. German "Umlaute") on Windows. That problem is particularly relevant, if your username includes a "Umlaut" (e.g. "Max Müller").

The existing implementation assumed that the tempdir() would not include special characters, but this is not true, as you can see:

```
> library(polmineR)
> use("polmineR") ... activating corpus: GERMAPARLMINI
... path includes non-ASCII characters, moving binary corpus data to temporary data directory (C:/Users/Andreas Blätte/AppData/Local/Temp/RtmpKgcSfw/polmineR_data_dir/germaparlmini)
... activating corpus: REUTERS
... path includes non-ASCII characters, moving binary corpus data to temporary data directory (C:/Users/Andreas Blätte/AppData/Local/Temp/RtmpKgcSfw/polmineR_data_dir/reuters)
> corpus() cl_new_corpus: can't locate <GERMAPARLMINI> in C:/Users/Andreas Blätte/AppData/Local/Temp/RtmpKgcSfw/polmineR_registry
attributes:cl_new_attribute_oldstyle(): called with NULL corpus cl_new_corpus: can't locate <REUTERS> in C:/Users/Andreas Blätte/AppData/Local/Temp/RtmpKgcSfw/polmineR_registry 
attributes:cl_new_attribute_oldstyle(): called with NULL corpus
 corpus size template
1 GERMAPARLMINI   -1     TRUE
2 REUTERS   -1     TRUE
``` 

A potential solution is to recover the Windows DOS file name using utils::shortPathName.

**Comment by PolMine** [comment] 2020-03-04 08:59
Returning to this exceptionally awkward issue of filenames with special characters, I want to close the issue because I am fairly sure that it is solved.

I had implemented the idea issued at the end of the initial issue that  `utils::shortPathName()` might solve the issue. So paths are adjusted in a manner Windows swallows if special characters are present in the file name.

Checking whether it really works is really tricky. This is how far I got: Using an old Windows machine with full admin rights,  I created an awful user name that would cause all the errors I would like to see: "Andreas Blätte".

Installing any package from source is actually quite impossible if you have this kind of awful user name, because R CMD INSTALL will abort early on. My interpretation of the message is that R CMD INSTALL cannot process non-ASCII characters properly. Copying the DESCRIPTION file fails, because the filename is buggy (encoding trash) where the special characters of the user name occur.

Using `devtools::install_github()` will fail either. However, it is possible to install binary R packages  from CRAN. Loading polmineR works, and simple operations on the console are not a problem.

There are limits to more systematic testing, because CRAN will not put the test suite into the package. However you can test whether examples work:

```r
tools::testInstalledPackages(pkg = "polmineR", types = "examples")
```

I see two NOTEs that path names are different - but this is expected behavior, as `shortPathName()` intendedly changes the path name. 

So my assumption is that handling path names with special characters has been addressed, and I will close this issue.

**Closed by PolMine** 2020-03-04 08:59 UTC
