### ISSUE TITLE
new error when creating speech_bundle | Error in names(y@objects) <- names(.Object) : 

### ISSUE THREAD

**Issue by ChristophLeonhardt** [PolMine/polmineR#82] opened 2019-04-29 19:18 UTC
New error during a tried and tested lda workflow. polmineR-Version: polmineR_0.7.11.9013

```{r}
library(polmineR)
use("GermaParl")
speeches <- as.speeches("GERMAPARL", s_attribute_date = "date", s_attribute_name = "speaker")
count_bundle <- polmineR::count(speeches, p_attribute = "word", verbose = TRUE)
... unfolding corpus positions
... adding ids for p-attribute 'word'
... performing count
... adding decoded p-attribute
... creating bundle of count objects

Error in names(y@objects) <- names(.Object) : 
  'names' attribute [162023] must be the same length as the vector [161465] 
```

Don't know if it helps, but anyways: length(speeches) == length(names(speeches)) is TRUE (both 162023). Seems like some speeches get dropped here?

Does happen with other corpora as well. GermaParlMini works though...

**Comment by ChristophLeonhardt** [comment] 2019-04-30 09:22
Reinstalling the dev version from GitHub seems to solve the problem. It's still version 0.7.11.9013 after the update. Maybe I missed an update in between which hasn't changed the version number? But solved, I guess!

**Comment by ablaette** [comment] 2019-04-30 20:29
Thanks a lot for raising the issue. This has really been nerve-wrecking, but I do think the issue is solved in a new version of polmineR on the development branch (v0.7.11.9014). 
The error you report results from several subcorpora having the same name, that's fairly easy to see. The cause is a bug in the refactored `as.speeches()`-method. It relies heavily on calling `split(). On one occasion, a vector of dates is splitted by itself. Now, if dates are not fully standardized, the call to `as.factor()` twists the order of the resulting list in a manner I had not expected. Unwantedly, some subcorpora then had the same name...  Be it as it may, the issue should be fixed.

**Comment by ChristophLeonhardt** [comment] 2019-04-30 21:12
Yes, v0.7.11.9014 solves the issue. Thanks for the swift response!

**Closed** 2019-04-30 21:19 UTC
